image: ${SCRIPTS_IMAGE_NAME}:${SCRIPTS_IMAGE_TAG}

variables:
  SCRIPTS_IMAGE_NAME: "alpine"
  SCRIPTS_IMAGE_TAG: "3.9"
  PAGES_TARGET_FOLDER: "public"
  PAGES_SOURCE_FOLDER: "src/*"
  SCRIPTS_SKIP_TEST: ""
  SCRIPTS_SKIP_ZIP: ""

include:
  - project: 'singletonsd/pipelines/common'
    file: '/src/.gitlab-ci-pages.yml'

stages:
  - test
  - build
  - deploy

test:
  image: koalaman/shellcheck-alpine:stable
  stage: test
  before_script:
    - apk add --no-cache bash curl
  script:
    - mkdir -p binaries
    - curl -o binaries/bash_script_test_standalone.sh -L https://singletonsd.gitlab.io/scripts/common/latest/bash_script_test_standalone.sh
    - chmod +x binaries/bash_script_test_standalone.sh
    - ./binaries/bash_script_test_standalone.sh
  except:
    variables:
      - $SCRIPTS_SKIP_TEST == "true"

zip:
  stage: build
  before_script:
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then
        export TARGET_FOLDER=${PAGES_TARGET_FOLDER}/latest;
      else
        export TARGET_FOLDER=${PAGES_TARGET_FOLDER}/${CI_COMMIT_REF_NAME};
      fi
    - apk add --no-cache bash curl zip
  script:
    - mkdir -p binaries
    - curl -o binaries/zip_files.sh -L https://singletonsd.gitlab.io/scripts/common/latest/zip_files.sh
    - chmod +x binaries/zip_files.sh
    - ./binaries/zip_files.sh
    - mkdir -p "${TARGET_FOLDER}"
    - ./binaries/zip_files.sh
  except:
    variables:
      - $SCRIPTS_SKIP_ZIP == "true"
  artifacts:
    paths:
      - public
