image: alpine:3.9

variables:
  PAGES_TARGET_FOLDER: "public"
  PAGES_SOURCE_FOLDER: "dist"

stages:
  - deploy

pages:
  stage: deploy
  before_script:
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then
        export TARGET_FOLDER=${PAGES_TARGET_FOLDER}/latest;
      else
        export TARGET_FOLDER=${PAGES_TARGET_FOLDER}/${CI_COMMIT_REF_NAME};
      fi
  script:
    - rm -rf "${TARGET_FOLDER}"
    - mkdir -p "${TARGET_FOLDER}"
    - cp -r ${PAGES_SOURCE_FOLDER} "${TARGET_FOLDER}"
    - ls -R public
  artifacts:
    paths:
      - public
